version: '3'

networks:
  default:
    driver: bridge

services:
  php:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      - default
    ports:
      - '8080:80'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - default
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
    - '8899:80'

  db:
    container_name: mysql
    image: 'mysql:latest'
    networks:
      - default
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yiicheck
      MYSQL_USER: root
      MYSQL_PASSWORD: root